package com.golmok.golmokstar.enums;

public enum PlaceType {
    UNKNOWN, BAKERY, BAR, CAFE, MEAL_DELIVERY, MEAL_TAKEAWAY, RESTAURANT,
    AMUSEMENT_PARK, AQUARIUM, BOWLING_ALLEY, CAMPGROUND, CASINO, GYM, MOVIE_THEATER,
    NIGHT_CLUB, STADIUM, ZOO, RV_PARK,
    ART_GALLERY, BOOK_STORE, LIBRARY, MUSEUM, TOURIST_ATTRACTION,
    SPA, PARK, HINDU_TEMPLE, MOSQUE, CHURCH, SYNAGOGUE,
    CLOTHING_STORE, DEPARTMENT_STORE, ELECTRONICS_STORE, FLORIST, FURNITURE_STORE,
    HARDWARE_STORE, HOME_GOODS_STORE, JEWELRY_STORE, SHOE_STORE, SHOPPING_MALL,
    STORE, SUPERMARKET, CONVENIENCE_STORE, LIQUOR_STORE,
    AIRPORT, BUS_STATION, LIGHT_RAIL_STATION, SUBWAY_STATION, TAXI_STAND,
    TRAIN_STATION, TRANSIT_STATION, PARKING, CAR_RENTAL, CAR_DEALER, CAR_REPAIR, CAR_WASH, GAS_STATION,
    ACCOUNTING, BANK, ATM, CITY_HALL, COURTHOUSE, EMBASSY, FIRE_STATION,
    INSURANCE_AGENCY, LAWYER, LOCAL_GOVERNMENT_OFFICE, POLICE, POST_OFFICE, REAL_ESTATE_AGENCY,
    DENTIST, DOCTOR, DRUGSTORE, HOSPITAL, PHARMACY,
    ELECTRICIAN, LOCKSMITH, MOVING_COMPANY, PAINTER, PLUMBER, ROOFING_CONTRACTOR, STORAGE, LAUNDRY;

    public static PlaceType fromString(String value) {
        try {
            return PlaceType.valueOf(value.toUpperCase()); // 대소문자 무시하고 변환
        } catch (IllegalArgumentException e) {
            return UNKNOWN; // 존재하지 않는 값이면 UNKNOWN 반환
        }
    }
}